-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Answers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "SerialNumber" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    CONSTRAINT "PK_Answers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Interviews"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer,
    "StartTime" timestamp with time zone NOT NULL,
    "FinishTime" timestamp with time zone,
    "Status" integer NOT NULL,
    "SurveyId" integer NOT NULL,
    CONSTRAINT "PK_Interviews" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Questions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "TypeAnswer" integer NOT NULL,
    "SerialNumber" integer NOT NULL,
    "SurveyId" integer NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Results"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "InterviewId" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "AnswerId" integer,
    "AnswerTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Results" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Surveys"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    "CreateTime" timestamp with time zone NOT NULL,
    "UpdateTime" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Surveys" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Answers"
    ADD CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId")
    REFERENCES public."Questions" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Answers_QuestionId"
    ON public."Answers"("QuestionId");


ALTER TABLE IF EXISTS public."Interviews"
    ADD CONSTRAINT "FK_Interviews_Surveys_SurveyId" FOREIGN KEY ("SurveyId")
    REFERENCES public."Surveys" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Interviews_SurveyId"
    ON public."Interviews"("SurveyId");


ALTER TABLE IF EXISTS public."Questions"
    ADD CONSTRAINT "FK_Questions_Surveys_SurveyId" FOREIGN KEY ("SurveyId")
    REFERENCES public."Surveys" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Results"
    ADD CONSTRAINT "FK_Results_Answers_AnswerId" FOREIGN KEY ("AnswerId")
    REFERENCES public."Answers" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Results_AnswerId"
    ON public."Results"("AnswerId");


ALTER TABLE IF EXISTS public."Results"
    ADD CONSTRAINT "FK_Results_Interviews_InterviewId" FOREIGN KEY ("InterviewId")
    REFERENCES public."Interviews" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Results"
    ADD CONSTRAINT "FK_Results_Questions_QuestionId" FOREIGN KEY ("QuestionId")
    REFERENCES public."Questions" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Results_QuestionId"
    ON public."Results"("QuestionId");

INSERT INTO  public."Surveys" ("Name", "Description", "CreateTime", "UpdateTime", "IsActive")
VALUES 
('Отзывы клиентов', 'Опрос для сбора мнений клиентов', '2023-10-01 10:00:00', '2023-10-05 15:00:00', true),
('Удовлетворенность сотрудников', 'Внутренний опрос для сотрудников', '2023-10-02 09:00:00', NULL, true);

INSERT INTO public."Questions" ("Name", "TypeAnswer", "SerialNumber", "SurveyId")
VALUES 
('Насколько вы удовлетворены?', 1, 1, 1),
('Что мы можем улучшить?', 2, 2, 1),
('Как вы оцениваете своего руководителя?', 1, 1, 2),
('Какие льготы вы цените?', 2, 2, 2);

INSERT INTO public."Answers" ("Name", "SerialNumber", "QuestionId")
VALUES 
('Очень доволен', 1, 1),
('Доволен', 2, 1),
('Нейтрально', 3, 1),
('Не доволен', 4, 1),
('Очень не доволен', 5, 1),
('Лучшее обслуживание клиентов', 1, 2),
('Более быстрая доставка', 2, 2),
('Отлично', 1, 3),
('Хорошо', 2, 3),
('Средне', 3, 3),
('Плохо', 4, 3),
('Медицинская страховка', 1, 4),
('Гибкий график', 2, 4),
('Удаленная работа', 3, 4);

INSERT INTO public."Interviews" ("UserId", "StartTime", "FinishTime", "Status", "SurveyId")
VALUES 
(101, '2023-10-10 14:00:00', '2023-10-10 14:30:00', 1, 1),
(102, '2023-10-11 10:00:00', '2023-10-11 10:45:00', 1, 2);

INSERT INTO public."Results" ("InterviewId", "QuestionId", "AnswerId", "AnswerTime")
VALUES 
(1, 1, 2, '2023-10-10 14:05:00'),
(1, 2, 6, '2023-10-10 14:10:00'),
(2, 3, 8, '2023-10-11 10:10:00'),
(2, 4, 12, '2023-10-11 10:20:00');

END;